apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurants-app
  template:
    metadata:
      labels:
        app: restaurants-app
    spec:
      containers:
      - name: restaurants-app
        image: tendermulletacr.azurecr.io/restaurants-app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: restaurants-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: restaurants-app