apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurants-app
  template:
    metadata:
      labels:
        app: restaurants-app
    spec:
      containers:
      - name: restaurants-app
        image: restaurantsacr.azurecr.io/restaurants-app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: restaurants-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: restaurants-app

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: restaurants-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restaurants-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
