apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "restaurants-app-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "restaurants-app"
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
