apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"azurefile-pv"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"5Gi"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"azurefile-app"}}
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-app
  volumeMode: Filesystem
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: history-storage
    volumeAttributes:
      resourceGroup: DevOps-rg
      storageAccount: restaurantstfstatesa
      shareName: aksshare
      server: restaurantstfstatesa.privatelink.file.core.windows.net
