replicaCount: 1

image:
  repository: tendermulletacr.azurecr.io/restaurants-app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

service:
  type: LoadBalancer
  port: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []