replicaCount: 1

image:
  repository: restaurantsacr.azurecr.io/restaurants-app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 80

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

serviceAccount:
  create: true
  name: ""
