replicaCount: 1

image:
  repository: restaurantsacr.azurecr.io/restaurants-app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

service:
  type: LoadBalancer
  port: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: restaurant-recommendations.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

clusterIssuer:
name: letsencrypt-prod
email: raz.shoham@gmail.com

certificate:
name: restaurants-app-tls
commonName: your-ip-address.nip.io
dnsNames:
  - your-ip-address.nip.io