{{- if not (lookup "cert-manager.io/v1" "Certificate" .Release.Namespace "restaurants-app-tls") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: restaurants-app-tls
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: restaurants-app
    meta.helm.sh/release-namespace: default
spec:
  secretName: restaurants-app-tls
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: ClusterIssuer
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . }}
    {{- end }}
{{- end }}