apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restaurants-app.fullname" . }}
  labels:
    app: {{ include "restaurants-app.name" . }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: restaurants-app
    meta.helm.sh/release-namespace: default

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "restaurants-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "restaurants-app.name" . }}
    spec:
      dnsConfig:
        nameservers:
          - 168.63.129.16
      initContainers:
      - name: init-mount
        image: your-docker-username/your-image-name:tag
        command:
        - sh
        - -c
        - |
          mkdir -p /mnt/aksshare
          if [ ! -d "/etc/smbcredentials" ]; then
            mkdir /etc/smbcredentials
          fi
          echo "username=$(cat /etc/smbcredentials/username)" > /etc/smbcredentials/restaurantstfstatesa.cred
          echo "password=$(cat /etc/smbcredentials/password)" >> /etc/smbcredentials/restaurantstfstatesa.cred
          chmod 600 /etc/smbcredentials/restaurantstfstatesa.cred
          mount -t cifs //restaurantstfstatesa.file.core.windows.net/aksshare /mnt/aksshare -o credentials=/etc/smbcredentials/restaurantstfstatesa.cred,dir_mode=0777,file_mode=0777,serverino,nosharesock,actimeo=30
        volumeMounts:
        - name: smb-credentials
          mountPath: /etc/smbcredentials
          readOnly: true
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 443
        volumeMounts:
        - name: aksshare
          mountPath: /mnt/aksshare
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: history-storage
          mountPath: /app/history  # Directory where the application will store the request history
      volumes:
      - name: smb-credentials
        secret:
          secretName: smb-credentials
      - name: aksshare
        emptyDir: {}
      - name: history-storage
        persistentVolumeClaim:
          claimName: azurefile-pvc
