apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restaurants-app.fullname" . }}
  labels:
    app: {{ include "restaurants-app.name" . }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: restaurants-app
    meta.helm.sh/release-namespace: default

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "restaurants-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "restaurants-app.name" . }}
    spec:
      dnsConfig:
        nameservers:
          - 168.63.129.16
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 443
        volumeMounts:
        - name: aksshare
          mountPath: /mnt/aksshare
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        volumeMounts:
        - name: history-storage
          mountPath: /app/history  # Directory where the application will store the request history
      volumes:
      - name: smb-credentials
        secret:
          secretName: smb-credentials
      - name: aksshare
        emptyDir: {}
      - name: history-storage
        persistentVolumeClaim:
          claimName: azurefile-pvc
