apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restaurants-app.fullname" . }}
  labels:
    app: {{ include "restaurants-app.name" . }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: restaurants-app
    meta.helm.sh/release-namespace: default

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "restaurants-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "restaurants-app.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        volumeMounts:
        - name: history-storage
          mountPath: /app/history  # Directory where the application will store the request history
      volumes:
      - name: history-storage
        persistentVolumeClaim:
          claimName: azurefile-pvc
