apiVersion: batch/v1
kind: Job
metadata:
  name: create-pv-pvc
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "### Listing contents of the templates directory"
          ls -R templates
          echo "### Applying Role and RoleBinding"
          kubectl apply -f templates/role.yaml
          kubectl apply -f templates/rolebinding.yaml
          echo "### Deleting existing job if it exists"
          kubectl delete job create-pv-pvc --ignore-not-found
          echo "### Applying PersistentVolume"
          kubectl apply -f templates/persistent-volume.yaml
          echo "### Applying PersistentVolumeClaim"
          kubectl apply -f templates/persistent-volume-claim.yaml
      restartPolicy: OnFailure
