apiVersion: batch/v1
kind: Job
metadata:
  name: create-pv-pvc
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "### Applying Role and RoleBinding"
          echo "working directory is: "; pwd
          echo "The content is: ";ls -ltr
          echo "The content in target folder /home/ is: ";ls -ltr /home/
          echo "The content in target folder /home/runner/ is: ";ls -ltr /home/runner/
          echo "The content in target folder /home/runner/work/ is: ";ls -ltr /home/runner/work/
          echo "The content in target folder /home/runner/work/app1/ is: ";ls -ltr /home/runner/work/app1/
          echo "The content in target folder /home/runner/work/app1/app1 is: ";ls -ltr /home/runner/work/app1/app1/
          echo "The content in target folder /home/runner/work/app1/app1/restaurants-charts is: ";ls -ltr /home/runner/work/app1/app1/restaurants-charts/
          echo "The content in target folder /home/runner/work/app1/app1/restaurants-charts/templates is: ";ls -ltr /home/runner/work/app1/app1/restaurants-charts/templates/
          kubectl apply -f /home/runner/work/app1/app1/restaurants-charts/templates/role.yaml
          kubectl apply -f /home/runner/work/app1/app1/restaurants-charts/templates/rolebinding.yaml
          echo "### Deleting existing job if it exists"
          kubectl delete job create-pv-pvc --ignore-not-found
          echo "### Applying PersistentVolume"
          kubectl apply -f /home/runner/work/app1/app1/restaurants-charts/templates/persistent-volume.yaml
          echo "### Applying PersistentVolumeClaim"
          kubectl apply -f /home/runner/work/app1/app1/restaurants-charts/templates/persistent-volume-claim.yaml
      restartPolicy: OnFailure
