apiVersion: batch/v1
kind: Job
metadata:
  name: create-pv-pvc
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          if kubectl get job create-pv-pvc; then
            kubectl delete job create-pv-pvc
          fi
          kubectl apply -f /path/to/persistent-volume.yaml
          kubectl apply -f /path/to/persistent-volume-claim.yaml
      restartPolicy: OnFailure
