apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-app
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: "restaurantstfstatesa#aksshare"
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
