apiVersion: v1
kind: Service
metadata:
  name: {{ include "restaurants-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 443
  selector:
    app: {{ include "restaurants-app.name" . }}