{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "restaurants-app.serviceAccountName" . }}
  labels:
    helm.sh/chart: {{ include "restaurants-app.chart" . }}
    app.kubernetes.io/name: {{ include "restaurants-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: true
